Palindrome: Palindrome.o
	gcc -o $@ $^
Palindrome.o: Palindrome.c
	gcc -c $^
PalindromeRecursive: PalindromeRecursive.o
	gcc -o $@ $^
PalindromeRecursive.o: PalindromeRecursive.c
	gcc -c $^
clean:
	rm Palindrome PalindromeRecursive *.o
